import type {
  BrainCollectionSnapshot,
  BrainProjectSnapshot,
  BrainTaskSnapshot,
} from "./types";
import {
  isContentScanExcludedPath,
  resolveTodayJournalPath,
} from "./vault-paths";

/**
 * AI-facing, machine-maintained index of the vault.
 *
 * This module is pure and deterministic (no Date.now / randomness): the caller
 * supplies `generatedAt` and `today`, and the renderer sorts every list so the
 * same snapshot always produces the same Markdown. The desktop app writes the
 * result to `.ai/INDEX.md` and only rewrites it when the output actually
 * changes, so machines maintain it without ever touching the user-owned
 * `.ai/INSTRUCTIONS.md` canonical handoff file.
 */

/** Max unscheduled ideas listed in `.ai/INDEX.md` so the file stays a short map. */
export const VAULT_INDEX_UNSCHEDULED_LIMIT = 8;

export interface VaultIndexInput {
  /** Taipei date key (YYYY-MM-DD) used for the "today / overdue" summary. */
  today: string;
  /** ISO timestamp included at the top of the document (for provenance only). */
  generatedAt: string;
  tasks: BrainTaskSnapshot[];
  projects: BrainProjectSnapshot[];
  collections: BrainCollectionSnapshot[];
  /**
   * Vault-relative paths known to exist. Used to list today's journal without
   * inventing a file. Optional so callers that only have entity snapshots still
   * get a stable map.
   */
  existingPaths?: readonly string[];
}

const HEADER = `# Second Brain — Vault Index

> Machine-generated by Second Brain Workspace. Do not edit by hand; it is
> regenerated when the vault content changes. Read \`.ai/INSTRUCTIONS.md\` first,
> then this map, then open only one listed file.
`;

function inlineCell(value: string | null | undefined): string {
  const text = (value ?? "")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .trim();
  return text || "—";
}

function toMarkdownTable(headers: string[], rows: (string | null)[][]): string {
  const header = `| ${headers.map(inlineCell).join(" | ")} |`;
  const divider = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map(
    (row) => `| ${row.map(inlineCell).join(" | ")} |`,
  );
  return [header, divider, ...body].join("\n");
}

function approach(value: string | null | undefined): string {
  return value == null || value === "" ? "—" : value;
}

function isIndexablePath(relativePath: string | null | undefined): boolean {
  if (!relativePath) return true;
  return !isContentScanExcludedPath(relativePath);
}

function isInProgressProject(project: BrainProjectSnapshot): boolean {
  if (!isIndexablePath(project.sourcePath)) return false;
  const status = (project.status ?? "").toLocaleLowerCase();
  return status !== "done" && status !== "archived";
}

function isOpenTask(task: BrainTaskSnapshot): boolean {
  return task.status !== "done";
}

function compareIndexTasks(
  left: BrainTaskSnapshot,
  right: BrainTaskSnapshot,
): number {
  return (
    (left.taskDate ?? "9999-99-99").localeCompare(right.taskDate ?? "9999-99-99") ||
    (left.startTime ?? "99:99").localeCompare(right.startTime ?? "99:99") ||
    left.rank.localeCompare(right.rank) ||
    left.title.localeCompare(right.title) ||
    (left.sourcePath ?? "").localeCompare(right.sourcePath ?? "") ||
    (left.id ?? "").localeCompare(right.id ?? "")
  );
}

function sortedOpen(
  tasks: readonly BrainTaskSnapshot[],
  predicate: (task: BrainTaskSnapshot) => boolean,
): BrainTaskSnapshot[] {
  return tasks
    .filter(
      (task) =>
        isOpenTask(task) &&
        isIndexablePath(task.sourcePath) &&
        predicate(task),
    )
    .sort(compareIndexTasks);
}

function todayIndexTasks(
  tasks: readonly BrainTaskSnapshot[],
  today: string,
): BrainTaskSnapshot[] {
  return sortedOpen(tasks, (task) => task.taskDate === today);
}

function overdueIndexTasks(
  tasks: readonly BrainTaskSnapshot[],
  today: string,
): BrainTaskSnapshot[] {
  return sortedOpen(
    tasks,
    (task) => Boolean(task.taskDate && task.taskDate < today),
  );
}

function unscheduledIndexTasks(
  tasks: readonly BrainTaskSnapshot[],
): BrainTaskSnapshot[] {
  return sortedOpen(tasks, (task) => !task.taskDate);
}

function formatVisibleSchedule(task: BrainTaskSnapshot): string {
  const parts: string[] = [];
  if (task.taskDate) parts.push(`⏳ ${task.taskDate}`);
  if (task.startTime) parts.push(`⏰ ${task.startTime}`);
  if (task.durationMinutes != null) parts.push(`⏱ ${task.durationMinutes}m`);
  return parts.join(" ");
}

function scheduledTaskRows(tasks: BrainTaskSnapshot[]): (string | null)[][] {
  return tasks.map((item) => [
    item.title,
    formatVisibleSchedule(item),
    item.projectName,
    item.sourcePath,
  ]);
}

function ideaRows(tasks: BrainTaskSnapshot[]): (string | null)[][] {
  return tasks.map((item) => [item.title, item.sourcePath]);
}

function renderTaskTable(
  headers: string[],
  rows: (string | null)[][],
  empty: string,
): string {
  return rows.length === 0 ? empty : toMarkdownTable(headers, rows);
}

function projectRows(projects: BrainProjectSnapshot[]): (string | null)[][] {
  const sorted = [...projects].sort(
    (a, b) =>
      a.name.localeCompare(b.name) ||
      (a.id ?? "").localeCompare(b.id ?? ""),
  );
  return sorted.map((project) => [
    project.name,
    project.status,
    project.progress == null ? "—" : `${project.progress}%`,
    project.sourcePath,
  ]);
}

function knowledgeRows(collections: BrainCollectionSnapshot[]): (string | null)[][] {
  const sorted = [...collections].sort(
    (a, b) =>
      (a.category ?? "").localeCompare(b.category ?? "") ||
      a.name.localeCompare(b.name) ||
      (a.sourcePath ?? "").localeCompare(b.sourcePath ?? ""),
  );
  return sorted.map((collection) => [
    collection.name,
    approach(collection.category),
    collection.sourcePath,
  ]);
}

function importantKnowledge(
  collections: readonly BrainCollectionSnapshot[],
): BrainCollectionSnapshot[] {
  return collections.filter(
    (collection) =>
      collection.importance === 1 && isIndexablePath(collection.sourcePath),
  );
}

function aiInstructions(): string {
  return `## Operating instructions for AI

1. Read \`.ai/INSTRUCTIONS.md\` first; it is authoritative for this vault.
2. Read this INDEX next; it is only a map of what exists right now.
3. Open only one listed file. Do not read the entire inbox.
4. Preserve BOM, CRLF, indentation and unknown tokens. Do not invent files that are not listed.
`;
}

export function renderVaultIndex(input: VaultIndexInput): string {
  const today = input.today;
  const projects = input.projects.filter(isInProgressProject);
  const knowledge = importantKnowledge(input.collections);
  const todayTasks = todayIndexTasks(input.tasks, today);
  const overdue = overdueIndexTasks(input.tasks, today);
  const ideas = unscheduledIndexTasks(input.tasks);
  const shownIdeas = ideas.slice(0, VAULT_INDEX_UNSCHEDULED_LIMIT);
  const hidden = ideas.length - shownIdeas.length;
  const scheduledHeaders = ["標題", "時間", "專案", "路徑"];
  const ideaHeaders = ["標題", "路徑"];
  const journalPath = resolveTodayJournalPath(
    today,
    input.existingPaths ?? [],
  );

  const projectTable =
    projects.length === 0
      ? "_No in-progress projects._"
      : toMarkdownTable(
          ["名稱", "狀態", "進度", "路徑"],
          projectRows(projects),
        );
  const knowledgeTable =
    knowledge.length === 0
      ? "_No important knowledge._"
      : toMarkdownTable(
          ["標題", "分類", "路徑"],
          knowledgeRows(knowledge),
        );

  const lines = [
    HEADER,
    `Generated at: ${input.generatedAt}`,
    "",
    "## In-progress projects 進行中專案",
    "",
    projectTable,
    "",
    `## Today's tasks 今日任務（${today}）`,
    "",
    renderTaskTable(
      scheduledHeaders,
      scheduledTaskRows(todayTasks),
      "_No tasks scheduled for today._",
    ),
    "",
    "## Overdue tasks 逾期任務",
    "",
    renderTaskTable(
      scheduledHeaders,
      scheduledTaskRows(overdue),
      "_No overdue tasks._",
    ),
    "",
    "## Important knowledge 常用知識",
    "",
    knowledgeTable,
    "",
    `## Today's journal 今日日誌（${today}）`,
    "",
    journalPath ? `\`${journalPath}\`` : "_尚無_",
    "",
    "## Unscheduled ideas 未排程想法",
    "",
    renderTaskTable(
      ideaHeaders,
      ideaRows(shownIdeas),
      "_No unscheduled ideas._",
    ),
  ];
  if (hidden > 0) {
    lines.push("", `_…and ${hidden} more unscheduled ideas not listed._`);
  }
  lines.push("", aiInstructions());
  return lines.join("\n");
}
