import type {
  BrainCollectionSnapshot,
  BrainProjectSnapshot,
  BrainTaskSnapshot,
} from "./types";
import { getTodayTasks, splitTodayTasks } from "./today";

/**
 * AI-facing, machine-maintained index of the vault.
 *
 * This module is pure and deterministic (no Date.now / randomness): the caller
 * supplies `generatedAt` and `today`, and the renderer sorts every list so the
 * same snapshot always produces the same Markdown. The desktop app writes the
 * result to `.ai/INDEX.md` and only rewrites it when the output actually
 * changes, so machines maintain it without ever touching the user-owned
 * `.ai/INSTRUCTIONS.md` canonical handoff file.
 */

export interface VaultIndexInput {
  /** Taipei date key (YYYY-MM-DD) used for the "today / overdue" summary. */
  today: string;
  /** ISO timestamp included at the top of the document (for provenance only). */
  generatedAt: string;
  tasks: BrainTaskSnapshot[];
  projects: BrainProjectSnapshot[];
  collections: BrainCollectionSnapshot[];
}

const PROMOTIONAL_HEADER = `# Second Brain — Vault Index

> Machine-generated by Second Brain Workspace. Do not edit by hand; it is
> regenerated when the vault content changes. Your human-owned instructions
> live in \`.ai/INSTRUCTIONS.md\` — read that first for what to do, then use this
> index to see what exists.

## Give this to your AI

> You are now connected to a local-first Markdown "second brain". Start by
> reading \`.ai/INSTRUCTIONS.md\` (the human-authored rules), then \`.ai/INDEX.md\`
> (this file), then use the task/project/collection folders listed below to do
> project management and maintain the task list. Never upload Markdown bodies;
> edit the files in place and preserve their BOM / line endings / indentation.
`;

const ENCODING_SPEC = `## On-disk encoding (source of truth)

Everything is ordinary Markdown in the vault. The four entity kinds:

- **Task** — a list line anywhere, shaped like:

  \`\`\`
  - [ ] #task Write the report [[Project Name]] ⏳ 2026-08-15 ⏰ 09:30 ⏱ 30m

    ## Notes
    ...
  \`\`\`

  Optional fields ride the line (priority/date/time/project). Everything
  indented under that list item — checklists, paragraphs, headings — belongs
  to the same task until the next unindented \`- [ ] #task\` line. That is how
  Obsidian and AI group a project task with its notes. Do not park notes at
  the bottom of the file. Legacy HTML comment blocks are still read, then
  rewritten as indented notes on the next save.

  The trailing \`publisher-task:{...}\` token is a data-format compatibility
  marker only, not a product dependency.

- **Project** — a file under \`Projects/\` with YAML frontmatter:

  \`\`\`
  ---
  type: project
  publisher_id: <uuid>
  status: planning        # planning | active | paused | done | archived
  area: <business area>
  priority: <1-3>
  progress: 0
  focus_today: false
  start_date:
  end_date:
  completed_at:
  ---
  # Title
  \`\`\`

- **Collection** — a file under \`Collections/\` with YAML frontmatter:

  \`\`\`
  ---
  type: collection
  publisher_id: <uuid>
  category: 提示詞/投資分析    # category field; 提示詞/* = reusable prompt
  importance: <1-3>
  ---
  # Title
  \`\`\`

- **Intake** — unscheduled ideas use \`10-收件匣/待辦收件匣.md\` by default.

Reusable prompts are stored as \`type: collection\` with a \`category:\` starting
with \`提示詞/\`. Reusable templates live under \`90-模板/\`. AI handoff files live
under \`.ai/\` (never scanned as content).
`;

function inlineCell(value: string | null | undefined): string {
  const text = (value ?? "")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .trim();
  return text || "—";
}

function toMarkdownTable(headers: string[], rows: string[][]): string {
  const header = `| ${headers.map(inlineCell).join(" | ")} |`;
  const divider = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map(
    (row) => `| ${row.map(inlineCell).join(" | ")} |`,
  );
  return [header, divider, ...body].join("\n");
}

const PRIORITY_LABEL: Record<string, string> = {
  highest: "P1 最重要",
  high: "P2 高",
  medium: "P3 中",
  normal: "P4 一般",
  low: "P5 低",
};

function projectRows(projects: BrainProjectSnapshot[]): string[][] {
  const sorted = [...projects].sort(
    (a, b) =>
      a.name.localeCompare(b.name) ||
      (a.id ?? "").localeCompare(b.id ?? ""),
  );
  return sorted.map((project) => [
    project.name,
    project.status,
    approach(project.area),
    project.priority == null ? "—" : String(project.priority),
    project.progress == null ? "—" : `${project.progress}%`,
    approach(project.startDate),
    approach(project.endDate),
    project.focusToday ? "是" : "否",
  ]);
}

function collectionRows(collections: BrainCollectionSnapshot[]): string[][] {
  const sorted = [...collections].sort(
    (a, b) =>
      (a.category ?? "").localeCompare(b.category ?? "") ||
      a.name.localeCompare(b.name),
  );
  return sorted.map((collection) => [
    collection.name,
    approach(collection.category),
    collection.importance == null
      ? "—"
      : String(collection.importance),
  ]);
}

function approach(value: string | null | undefined): string {
  return value == null || value === "" ? "—" : value;
}

function taskSummary(
  tasks: BrainTaskSnapshot[],
  projects: BrainProjectSnapshot[],
  today: string,
): string {
  const open = tasks.filter((task) => task.status !== "done");
  const byStatus = (status: string) =>
    open.filter((task) => task.status === status).length;
  const { overdue, today: todayTasks } = splitTodayTasks(
    tasks,
    projects,
    today,
  );
  const important =
    [...getTodayTasks(tasks, projects, today)].find(
      (task) => task.priority === "highest",
    ) ?? null;

  const lines = [
    "## Task summary",
    "",
    `- 待辦 todo: ${byStatus("todo")}`,
    `- 執行 doing: ${byStatus("doing")}`,
    `- 等待 waiting: ${byStatus("waiting")}`,
    `- 完成 done: ${tasks.filter((task) => task.status === "done").length}`,
    `- 逾期 overdue（${today}）: ${overdue.length}`,
    `- 今日 today（${today}）: ${todayTasks.length}`,
    important
      ? `- 今日最重要 most-important: ${inlineCell(important.title)}`
      : "- 今日最重要 most-important: 尚未選定",
    "",
  ];
  return lines.join("\n");
}

function aiInstructions(): string {
  return `## Operating instructions for AI

1. Read \`.ai/INSTRUCTIONS.md\` first; it is authoritative for this vault.
2. To add a task, append a Markdown list line in the relevant file:

   \`\`\`
   - [ ] #task <title> [[<Project name>]] ⏳ <YYYY-MM-DD> ⏰ <HH:MM> ⏱ <minutes>m

     Optional notes as ordinary indented Markdown.
   \`\`\`

   The scanner assigns an id automatically; do not invent \`publisher_id\` values.
   Preserve existing text, BOM, CRLF, indentation and unknown tokens exactly.
3. To create a project or collection, write a new file under \`Projects/\` or
   \`Collections/\` with the frontmatter shown above; keep \`publisher_id\` a fresh
   UUID and \`status: planning\` for projects.
4. Reusable prompts live in \`Collections/\` with \`category: 提示詞/…\`; reuse
   them instead of duplicating guidance.
5. Work through this vault as a project manager: turn unclear thoughts into
   idea-inbox tasks, schedule by date, and surface what is most important.
`;
}

export function renderVaultIndex(input: VaultIndexInput): string {
  const folders = `## Folder conventions

| Folder | Purpose |
| --- | --- |
| \`.ai/\` | AI handoff: \`INSTRUCTIONS.md\` (human) + \`INDEX.md\` (auto) |
| \`10-收件匣/\` | Intake inbox (unscheduled ideas) |
| \`Projects/\` | Outcome projects (\`type: project\`) |
| \`Collections/\` | References & reusable prompts (\`type: collection\`) |
| \`90-模板/\` | Reusable entity templates (not scanned as content) |
| \`Prompts/\` | Prompt library scaffolding (optional) |
`;

  const projectTable =
    input.projects.length === 0
      ? "_No projects yet._"
      : toMarkdownTable(
          ["名稱", "狀態", "領域", "優先", "進度", "開始", "結束", "今日焦點"],
          projectRows(input.projects),
        );
  const collectionTable =
    input.collections.length === 0
      ? "_No collections yet._"
      : toMarkdownTable(
          ["名稱", "分類", "重要性"],
          collectionRows(input.collections),
        );
  const promptCollections = input.collections.filter(
    (collection) =>
      (collection.category ?? "").toLowerCase().startsWith("提示詞"),
  );

  return [
    PROMOTIONAL_HEADER,
    "",
    `Generated at: ${input.generatedAt}`,
    "",
    folders,
    "",
    ENCODING_SPEC,
    "",
    "## Projects",
    "",
    projectTable,
    "",
    "## Collections",
    "",
    collectionTable,
    "",
    "## Reusable prompts (提示詞)",
    "",
    promptCollections.length === 0
      ? "_No reusable prompts yet._"
      : promptCollections
          .map((collection) => `- **${inlineCell(collection.name)}** — ${inlineCell(collection.category)}`)
          .join("\n"),
    "",
    taskSummary(input.tasks, input.projects, input.today),
    "",
    aiInstructions(),
    "",
  ].join("\n");
}
