export type UiLanguage = "zh-TW" | "en";
export type UiTheme = "light" | "dark";
export type UiDensity = "comfortable" | "compact";
export type UiDetailSurface = "dialog" | "panel";

export interface UiPreferences {
  language: UiLanguage;
  theme: UiTheme;
  density: UiDensity;
  detailSurface: UiDetailSurface;
}

export const UI_PREFERENCES_KEY = "second-brain.uiPreferences";

export const DEFAULT_UI_PREFERENCES: UiPreferences = {
  language: "zh-TW",
  theme: "light",
  density: "comfortable",
  detailSurface: "dialog",
};

export function normalizeUiPreferences(value: unknown): UiPreferences {
  if (!value || typeof value !== "object") return DEFAULT_UI_PREFERENCES;
  const candidate = value as Partial<UiPreferences>;
  if (
    (candidate.language !== "zh-TW" && candidate.language !== "en")
    || (candidate.theme !== "light" && candidate.theme !== "dark")
  ) return DEFAULT_UI_PREFERENCES;
  return {
    language: candidate.language,
    theme: candidate.theme,
    density: candidate.density === "compact" ? "compact" : "comfortable",
    detailSurface: candidate.detailSurface === "panel" ? "panel" : "dialog",
  };
}

const ENGLISH: Record<string, string> = {
  "app.name": "Second Brain Workspace",
  "app.tagline": "Tasks and projects hub",
  "app.language": "Switch language",
  "app.theme": "Switch color theme",
  "app.theme.light": "Use light theme",
  "app.theme.dark": "Use dark theme",
  "settings.language": "Language",
  "settings.language.hint": "Choose the interface language. You can change it any time.",
  "settings.language.zh": "Traditional Chinese",
  "settings.language.en": "English",
  "settings.theme": "Appearance",
  "settings.theme.hint": "Light is easier by day; dark is easier at night. The sun/moon button in the top-right also switches this.",
  "settings.theme.light": "Light",
  "settings.theme.dark": "Dark",
  "settings.detailSurface": "Task and project detail",
  "settings.detailSurface.hint": "Choose how detail opens on wide windows. Narrow windows always use the full width.",
  "settings.detailSurface.dialog": "Centered dialog",
  "settings.detailSurface.dialogHint": "A wide sheet over a dimmed page, with more room for writing.",
  "settings.detailSurface.panel": "Side panel",
  "settings.detailSurface.panelHint": "Docked to the right so the current list remains visible and usable.",
  "app.sidebar": "Toggle sidebar",
  "app.online": "Online",
  "app.offline": "Offline mode",
  "app.more": "More",
  "app.search": "Search tasks, projects, and knowledge",
  "app.showCompleted": "Show completed",
  "app.hideCompleted": "Hide completed",
  "app.quickAdd": "Quick add task",
  "app.close": "Close",
  "app.save": "Save changes",
  "app.cancel": "Cancel",
  "app.undo": "Undo last change (drag, edit, delete)",
  "app.redo": "Redo last undone change",
  "app.create": "Create",
  "app.creating": "Creating…",
  "app.unassigned": "Unassigned",
  "app.uncategorized": "Uncategorized",
  "app.notSet": "Not set",
  "app.noContent": "No content yet",
  "view.today": "Today",
  "view.calendar": "Calendar",
  "view.board": "Board",
  "view.projects": "Projects",
  "view.collections": "Knowledge",
  "view.sync": "Settings",
  "view.today.title": "Today focus",
  "view.calendar.title": "Task calendar",
  "view.board.title": "Work board",
  "view.projects.title": "Project overview",
  "view.collections.title": "Knowledge",
  "view.sync.title": "Settings",
  "task.status.idea": "Idea inbox",
  "task.status.ideaHelp": "Not committed yet",
  "task.status.todo": "To do",
  "task.status.todoHelp": "Ready to start",
  "task.status.doing": "In progress",
  "task.status.doingHelp": "Actively moving forward",
  "task.status.waiting": "Waiting",
  "task.status.waitingHelp": "Waiting for a reply, material, approval, date, or another external condition",
  "task.status.done": "Done",
  "task.status.doneHelp": "Completed tasks",
  "task.action.important": "Mark as most important",
  "task.action.reopen": "Reopen task",
  "task.action.complete": "Mark complete",
  "task.action.edit": "Edit task",
  "task.action.delete": "Delete permanently",
  "task.action.promote": "Promote to project",
  "task.action.rename": "Rename",
  "task.action.priority": "Priority",
  "task.action.scheduleToday": "Schedule today",
  "task.hint.editTitle": "Double-click to edit",
  "task.hint.editPriority": "Click or double-click to set priority",
  "today.resizeDuration": "Drag to change duration",
  "task.field.title": "Task title",
  "task.field.status": "Status",
  "task.field.date": "Planned date",
  "task.field.startTime": "Start time",
  "task.field.duration": "Duration",
  "task.field.priority": "Priority",
  "task.field.project": "Project",
  "task.priority.highest": "Top",
  "task.priority.high": "High",
  "task.priority.medium": "Medium",
  "task.priority.normal": "Normal",
  "task.priority.low": "Low",
  "task.priority.label": "Priority {code}: {label}",
  "quick.title": "Quick add task",
  "quick.content": "Content",
  "quick.placeholder": "What is on your mind?",
  "quick.titleLabel": "Title",
  "quick.idea": "Start in idea inbox",
  "quick.ideaHelp": "No commitment or planned date yet; drag it to the calendar or To do when ready.",
  "quick.important": "Make it today's top task",
  "quick.importantDisabled": "Turn off idea inbox and choose a date first",
  "quick.importantHelp": "Only one per day; the previous one becomes high priority",
  "quick.guidance": "Capture guidance",
  "quick.guidance.taskTitle": "One step or an unclear thought",
  "quick.guidance.task": "Start in idea inbox",
  "quick.guidance.projectTitle": "Multiple actions with a clear outcome",
  "quick.guidance.project": "Create a project",
  "quick.guidance.collectionTitle": "Reusable information without a deadline",
  "quick.guidance.collection": "Add knowledge",
  "quick.create": "Create task",
  "quick.keyboard": "Enter create · Esc close",
  "picker.searchPlaceholder": "Search projects…",
  "picker.searchCategory": "Search or add a category…",
  "picker.chooseProject": "Choose a project…",
  "picker.chooseCategory": "Choose a category…",
  "picker.none": "No project",
  "picker.noCategory": "No category",
  "picker.empty": "No matching project",
  "picker.create": "New project “{name}”",
  "picker.createCategory": "New category “{name}”",
  "picker.creating": "Creating…",
  "board.lane.add": "Add a task to this lane",
  "board.lane.placeholder": "Task title · Enter to add",
  "board.view": "View style",
  "board.view.board": "Board",
  "board.view.table": "Table",
  "board.view.list": "List",
  "project.tasks.title": "Project tasks",
  "project.tasks.add": "Add a task to this project…",
  "project.tasks.create": "New task",
  "confirm.deleteAgain": "Delete permanently",
  "confirm.deleteMessage": "This removes the item from the Markdown folder on this computer. You can undo with Ctrl+Z.",
  "task.date.pick": "Open calendar to choose a date",
  "settings.localTitle": "This app writes to your folder",
  "settings.localHelp": "Checking a task, changing a date, or deleting something updates the Markdown files in the folder you selected. There is no separate database.",
  "settings.recoveryLocalHelp": "Every write first creates a SHA-256 verified ZIP backup, so you can recover if a save is interrupted.",
  "onboarding.title": "Welcome to your second brain",
  "onboarding.body": "This app stores tasks in a folder on this computer. Checking a box or changing a date writes that folder. There is no separate database.",
  "onboarding.task": "Task: one thing to do",
  "onboarding.project": "Project: several actions with a clear outcome",
  "onboarding.collection": "Knowledge: notes and prompts you will look up later",
  "onboarding.chooseFolder": "Choose a folder to start",
  "onboarding.skip": "Capture first, choose a folder later",
  "onboarding.architecture": "After you choose a folder, preview a few deletable sample notes. Existing files are not overwritten.",
  "today.eyebrow": "Today · {date}",
  "today.heading": "What to do today",
  "today.description": "Press N or the + button to add a task. Checking it marks it complete.",
  "today.start": "Start today",
  "today.journal": "Today's journal",
  "today.journal.hint": "A blank page. Type like Notion. Use the chips only if you want a heading.",
  "today.journal.hints": "Journal section hints",
  "today.journal.needFolder": "Choose a Markdown folder first so today's journal can be saved.",
  "today.journal.created": "Today's journal is ready",
  "today.journal.saved": "Journal saved",
  "today.template": "Daily task template",
  "today.template.manage": "Manage template",
  "today.template.collapse": "Collapse template",
  "today.timeline": "Today's timeline",
  "today.overdue": "Overdue tasks",
  "today.tasks": "Today's tasks",
  "today.emptyOverdue": "No overdue tasks.",
  "today.empty": "No tasks for today yet.",
  "today.emptyAction": "Add your first task",
  "today.unscheduled": "Not on the clock",
  "today.dropToSchedule": "Drag onto the timeline to set a start time.",
  "today.addAtTime": "Add a task at {time}",
  "today.editSelected": "Selected task",
  "calendar.previous": "Previous date range",
  "calendar.next": "Next date range",
  "calendar.today": "Today",
  "calendar.dayPlan": "Day plan",
  "calendar.emptyDay": "No tasks on this day.",
  "calendar.emptyDayAction": "Add your first task",
  "calendar.month": "Month",
  "calendar.week": "Week",
  "calendar.schedule": "Schedule",
  "calendar.planTimes": "Plan times",
  "calendar.sidebar": "Toggle day panel",
  "calendar.fullscreen": "Full screen",
  "calendar.exitFullscreen": "Exit full screen",
  "calendar.ideaTitle": "Idea inbox",
  "calendar.ideaHelp": "Draft tasks without a commitment; drag one onto the month, week, or day's schedule.",
  "calendar.noIdeas": "No unscheduled ideas.",
  "calendar.collapse": "Collapse",
  "calendar.items": "{count} items",
  "task.count.open": "{count} open",
  "task.count.doing": "{count} in progress",
  "project.tab.current": "Current",
  "project.tab.completed": "Completed",
  "project.tab.archived": "Archived",
  "project.view.list": "List view",
  "project.view.board": "Status board",
  "project.status.planning": "Planning",
  "project.status.active": "Active",
  "project.status.paused": "Paused",
  "project.status.done": "Completed",
  "project.status.archived": "Archived",
  "project.field.status": "Status",
  "project.field.category": "Category",
  "project.field.importance": "Importance",
  "project.field.startDate": "Start date",
  "project.field.endDate": "End date",
  "project.field.progress": "Progress {value}%",
  "project.importance.high": "High",
  "project.importance.medium": "Medium",
  "project.importance.low": "Low",
  "project.importance.unset": "Not set",
  "project.hint.editImportance": "Click or double-click to set importance",
  "project.focusToday": "Today focus",
  "project.action.add": "Add project",
  "project.action.open": "Open project board",
  "project.action.save": "Save project",
  "project.action.complete": "Complete project",
  "project.complete.title": "Complete this project?",
  "project.complete.message": "Complete \u201c{name}\u201d? This will also complete {count} open tasks and keep the full history.",
  "project.complete.messageNone": "Complete \u201c{name}\u201d? There are no open tasks. The full history is kept.",
  "project.complete.confirm": "Complete project",
  "project.complete.done": "Completed \u201c{name}\u201d",
  "project.action.reopen": "Reactivate project",
  "project.action.archive": "Archive project",
  "project.action.delete": "Delete permanently",
  "project.filter.status": "Filter by project status",
  "project.filter.importance": "Filter by importance",
  "project.filter.category": "Filter by category",
  "project.filter.allStatuses": "All statuses",
  "project.filter.allImportance": "All importance",
  "project.filter.allCategories": "All categories",
  "project.sort": "Sort projects",
  "project.sort.importance": "Importance",
  "project.sort.status": "Status",
  "project.sort.name": "Name",
  "project.sort.endDate": "Due date",
  "project.empty": "No projects match these filters.",
  "project.emptyHelp": "Create a project to turn a clear outcome into tracked work, or adjust the filters.",
  "project.emptyFirst": "No projects yet.",
  "project.emptyFirstHelp": "Add a project, or create one from a template later.",
  "project.emptyFirstAction": "Create from template",
  "project.period.none": "No dates",
  "project.date.undecided": "TBD",
  "collection.title": "Knowledge",
  "collection.description": "Long-term notes and prompts do not need project status or deadlines.",
  "collection.action.add": "Add knowledge",
  "collection.action.delete": "Delete knowledge",
  "collection.fillCopy": "Fill variables & copy",
  "collection.fillHelp": "Fill each variable below; the completed prompt is copied to your clipboard.",
  "collection.copy": "Copy prompt",
  "collection.filter.category": "Filter knowledge by category",
  "collection.filter.importance": "Filter knowledge by importance",
  "collection.empty": "No knowledge notes yet.",
  "collection.emptyHelp": "Create a long-term note, or import prompts from the AI Prompts+ extension JSON.",
  "collection.select": "Select a knowledge note to read its Markdown content.",
  "collection.contentHint": "No content yet; add it directly in Markdown.",
  "entity.project.title": "Add planning project",
  "entity.project.help": "For a clear outcome that needs multiple actions.",
  "entity.collection.title": "Add knowledge",
  "entity.collection.help": "For notes and prompts you will revisit without a completion deadline.",
  "knowledge.action.save": "Save as knowledge",
  "knowledge.save.title": "Save as knowledge",
  "knowledge.save.help": "Creates a long-term note. The original task or journal is left unchanged.",
  "project.relatedKnowledge": "Related knowledge",
  "project.relatedKnowledge.empty": "No linked knowledge yet.",
  "entity.field.name": "Name",
  "entity.field.category": "Category",
  "entity.field.importance": "Importance",
  "search.dialog": "Search tasks, projects, and knowledge",
  "search.keyword": "Search keywords",
  "search.placeholder": "A + B for OR; A & B for AND; quotes for phrases",
  "search.sort": "Sort results",
  "search.relevance": "Relevance",
  "search.date": "Date",
  "search.filter.status": "Filter by status",
  "search.filter.kind": "Filter by type",
  "search.allStatuses": "All statuses",
  "search.open": "Open",
  "search.completed": "Completed & archived",
  "search.allKinds": "All types",
  "search.kind.task": "Task",
  "search.kind.project": "Project",
  "search.kind.collection": "Knowledge",
  "search.results": "{count} results",
  "search.empty": "No matching tasks, projects, or knowledge.",
  "search.help": "↑↓ Select · Enter open · Esc close",
  "search.goSettings": "Go to settings",
  "board.back": "Back to projects",
  "board.clearFilter": "Clear project filter",
  "board.projectFilter": "Filter board by project",
  "board.title": "Project task board",
  "board.filteredTitle": "{name} · Task board",
  "board.description": "Drag cards to change stages; the idea inbox contains work you have not committed to yet.",
  "board.table.description": "The same tasks as a spreadsheet. Change status, project, or date in place.",
  "board.list.description": "A compact list grouped by stage.",
  "board.filteredDescription": "Only tasks from this project are shown.",
  "board.allProjects": "All projects",
  "board.dropHere": "Drop here",
  "board.moveUp": "Move up",
  "board.moveDown": "Move down",
  "sync.folder": "Markdown folder",
  "sync.folderHelp": "Use the Windows folder picker instead of typing a path.",
  "sync.notSelected": "Not selected",
  "sync.browse": "Browse folder",
  "sync.manualPath": "Or enter a path manually",
  "sync.useFolder": "Use this folder",
  "sync.cloud": "Cloud sync service",
  "sync.cloudHelp": "Cloud sync is optional. The open-source build is local-first and never uploads Markdown body content.",
  "sync.save": "Save",
  "sync.pairing": "Secure pairing",
  "sync.pairingHelp": "The website only needs the 8-character code below; no UUID or secret is required.",
  "sync.paired": "Secure pairing complete",
  "sync.pairedHelp": "You can now run the first sync",
  "sync.enterCode": "Enter this code on the website",
  "sync.openPairing": "Enter pairing code on website",
  "sync.startPairing": "Start pairing",
  "sync.recovery": "Sync & recovery",
  "sync.recoveryHelp": "Before every write, a SHA-256 verified ZIP is created. Background sync only runs when versions change.",
  "sync.firstConfirm": "One final confirmation needed",
  "sync.firstConfirmHelp": "Generate a safe preview first; automatic sync starts after the first successful sync.",
  "sync.pairFirst": "Complete pairing first",
  "sync.full": "Sync now",
  "sync.first": "Complete first sync",
  "sync.shadow": "Return to Shadow mode",
  "layout.title": "Organize into the new layout",
  "layout.help": "Preview files that will move into 專案/, 知識/, 日誌/, 收件匣/, 模板/, and 附件/. A verified ZIP backup is created first. Duplicate files are left in place so you can choose the original.",
  "layout.preview": "Preview organization",
  "layout.confirmTitle": "Confirm folder organization",
  "layout.confirmHelp": "These files will move to the new folders. Filenames stay the same, so Obsidian wikilinks keep working. Duplicates are not moved or deleted. Cancel leaves everything unchanged.",
  "layout.moves": "Will move",
  "layout.duplicates": "Duplicates (choose the original; nothing is deleted)",
  "layout.empty": "This folder already uses the new layout. Nothing needs to move.",
  "layout.apply": "Organize now",
  "layout.needFolder": "Choose a Markdown folder first.",
  "layout.done": "Folder layout updated",
  "layout.none": "Nothing to move",
};

const TRADITIONAL_CHINESE: Record<string, string> = {
  "app.name": "第二大腦工作台",
  "app.tagline": "任務與專案中心",
  "app.language": "切換語言",
  "app.theme": "切換色彩主題",
  "app.theme.light": "切換為淺色主題",
  "app.theme.dark": "切換為深色主題",
  "settings.language": "語言",
  "settings.language.hint": "選擇介面語言，隨時可以再改。",
  "settings.language.zh": "繁體中文",
  "settings.language.en": "English",
  "settings.theme": "外觀",
  "settings.theme.hint": "淺色適合白天，深色適合晚上。也可以用右上角的太陽／月亮按鈕快速切換。",
  "settings.theme.light": "淺色",
  "settings.theme.dark": "深色",
  "settings.detailSurface": "任務與專案的詳細內容",
  "settings.detailSurface.hint": "選擇寬螢幕開啟詳細內容的方式；窄螢幕一律使用全寬顯示。",
  "settings.detailSurface.dialog": "置中視窗",
  "settings.detailSurface.dialogHint": "以較寬的視窗覆蓋在變暗頁面上，提供較大的書寫空間。",
  "settings.detailSurface.panel": "側邊面板",
  "settings.detailSurface.panelHint": "停靠在右側，保留目前清單供檢視與切換。",
  "app.sidebar": "切換側面板",
  "app.online": "網路已連線",
  "app.offline": "離線模式",
  "app.more": "更多",
  "app.search": "搜尋任務、專案與知識",
  "app.showCompleted": "顯示已完成",
  "app.hideCompleted": "隱藏已完成",
  "app.quickAdd": "快速新增任務",
  "app.close": "關閉",
  "app.save": "儲存變更",
  "app.cancel": "取消",
  "app.undo": "復原上一個變更（拖曳、編輯、刪除）",
  "app.redo": "重做剛剛復原的變更",
  "app.create": "建立",
  "app.creating": "建立中…",
  "app.unassigned": "無專案",
  "app.uncategorized": "未分類",
  "app.notSet": "未設定",
  "app.noContent": "尚無內容",
  "view.today": "今日",
  "view.calendar": "日曆",
  "view.board": "看板",
  "view.projects": "專案",
  "view.collections": "知識",
  "view.sync": "設定",
  "view.today.title": "今日焦點",
  "view.calendar.title": "任務日曆",
  "view.board.title": "工作看板",
  "view.projects.title": "專案總覽",
  "view.collections.title": "知識",
  "view.sync.title": "設定",
  "task.status.idea": "想法匣",
  "task.status.ideaHelp": "還沒確定要執行",
  "task.status.todo": "待辦",
  "task.status.todoHelp": "已規劃、準備開始",
  "task.status.doing": "執行中",
  "task.status.doingHelp": "現在正在推進",
  "task.status.waiting": "等待",
  "task.status.waitingHelp": "等待回覆、素材、批准、日期或其他外部條件",
  "task.status.done": "完成",
  "task.status.doneHelp": "已完成的任務",
  "task.action.important": "設為最重要",
  "task.action.reopen": "重新開啟",
  "task.action.complete": "標記完成",
  "task.action.edit": "編輯任務",
  "task.action.delete": "永久刪除",
  "task.action.promote": "升級為專案",
  "task.action.rename": "重新命名",
  "task.action.priority": "優先度",
  "task.action.scheduleToday": "排到今天",
  "task.hint.editTitle": "雙擊編輯",
  "task.hint.editPriority": "點一下或雙擊調整優先度",
  "today.resizeDuration": "拖曳底部調整時長",
  "task.field.title": "任務名稱",
  "task.field.status": "狀態",
  "task.field.date": "規劃日",
  "task.field.startTime": "開始時間",
  "task.field.duration": "持續時間",
  "task.field.priority": "優先度",
  "task.field.project": "關聯專案",
  "task.priority.highest": "最重要",
  "task.priority.high": "高",
  "task.priority.medium": "中",
  "task.priority.normal": "一般",
  "task.priority.low": "低",
  "task.priority.label": "優先序 {code}：{label}",
  "quick.title": "快速新增任務",
  "quick.content": "內容",
  "quick.placeholder": "現在想到什麼？",
  "quick.titleLabel": "標題",
  "quick.idea": "先放想法匣",
  "quick.ideaHelp": "還不確定要執行，不安排規劃日；之後可拖到日曆或看板待辦。",
  "quick.important": "設為今日最重要",
  "quick.importantDisabled": "先取消想法匣並安排日期",
  "quick.importantHelp": "同一天只能有一項，原本的會自動降為高優先",
  "quick.guidance": "建立內容建議",
  "quick.guidance.taskTitle": "單一步驟或未釐清念頭",
  "quick.guidance.task": "先放想法匣",
  "quick.guidance.projectTitle": "需要多個行動與明確成果",
  "quick.guidance.project": "建立專案",
  "quick.guidance.collectionTitle": "會重複查閱且沒有期限",
  "quick.guidance.collection": "加入知識",
  "quick.create": "建立任務",
  "quick.keyboard": "Enter 建立 · Esc 關閉",
  "picker.searchPlaceholder": "搜尋專案…",
  "picker.searchCategory": "搜尋或新增分類…",
  "picker.chooseProject": "選擇專案…",
  "picker.chooseCategory": "選擇分類…",
  "picker.none": "無專案",
  "picker.noCategory": "無分類",
  "picker.empty": "沒有符合的專案",
  "picker.create": "新增專案「{name}」",
  "picker.createCategory": "新增分類「{name}」",
  "picker.creating": "建立中…",
  "board.lane.add": "在這欄直接新增任務",
  "board.lane.placeholder": "任務名稱 · Enter 新增",
  "board.view": "檢視樣式",
  "board.view.board": "看板",
  "board.view.table": "表格",
  "board.view.list": "清單",
  "project.tasks.title": "專案任務",
  "project.tasks.add": "新增任務到這個專案…",
  "project.tasks.create": "新增任務",
  "confirm.deleteAgain": "確定永久刪除",
  "confirm.deleteMessage": "這會從你電腦上選擇的 Markdown 資料夾刪除。本次可按 Ctrl+Z 復原。",
  "task.date.pick": "開啟日曆選擇日期",
  "settings.localTitle": "這裡的修改會寫進你的資料夾",
  "settings.localHelp": "在這裡打勾、改日期或刪除任務，都會直接更新你所選資料夾裡的 Markdown 檔。沒有另外一份資料庫。",
  "settings.recoveryLocalHelp": "每次寫入前會先建立可驗證的 ZIP 備份，中斷時可以復原。",
  "onboarding.title": "歡迎使用第二大腦工作台",
  "onboarding.body": "這是一個把任務存在你電腦資料夾的工具。打勾、改日期都會寫進那個資料夾，沒有另外一份資料庫。",
  "onboarding.task": "任務：今天要做的一件事",
  "onboarding.project": "專案：有成果的一組事",
  "onboarding.collection": "知識：以後要查的資料與提示詞",
  "onboarding.chooseFolder": "選擇資料夾，開始使用",
  "onboarding.skip": "先記下來，稍後再選資料夾",
  "onboarding.architecture": "選好資料夾後會預覽可刪的示範內容，不會覆寫既有檔案。",
  "today.eyebrow": "今日 · {date}",
  "today.heading": "今天要做的事",
  "today.description": "按 N 或右下角 ＋ 新增任務。勾選就是完成。",
  "today.start": "開始今天",
  "today.journal": "今天的日誌",
  "today.journal.hint": "空白畫布，直接打字。小標只在空白時當提示，不會預先寫進檔案。",
  "today.journal.hints": "日誌小標提示",
  "today.journal.needFolder": "請先選擇 Markdown 資料夾，才能建立今天的日誌。",
  "today.journal.created": "今天的日誌已就緒",
  "today.journal.saved": "日誌已儲存",
  "today.template": "每日任務模板",
  "today.template.manage": "管理模板",
  "today.template.collapse": "收合模板",
  "today.timeline": "今日時間軸",
  "today.overdue": "逾期任務",
  "today.tasks": "今日任務",
  "today.emptyOverdue": "沒有逾期任務。",
  "today.empty": "今天還沒有任務。",
  "today.emptyAction": "新增第一個任務",
  "today.unscheduled": "尚未排時間",
  "today.dropToSchedule": "拖到時間軸即可安排開始時間。",
  "today.addAtTime": "新增 {time} 的任務",
  "today.editSelected": "選取的任務",
  "calendar.previous": "上一個日期範圍",
  "calendar.next": "下一個日期範圍",
  "calendar.today": "今天",
  "calendar.dayPlan": "當日計畫",
  "calendar.emptyDay": "這天還沒有任務。",
  "calendar.emptyDayAction": "新增第一個任務",
  "calendar.month": "月曆",
  "calendar.week": "週曆",
  "calendar.schedule": "時間表",
  "calendar.planTimes": "安排時間",
  "calendar.sidebar": "切換日期側面板",
  "calendar.fullscreen": "全螢幕",
  "calendar.exitFullscreen": "離開全螢幕",
  "calendar.ideaTitle": "想法匣",
  "calendar.ideaHelp": "尚未承諾執行的草稿任務；拖到月曆、週曆或當日時間表即可排入行程。",
  "calendar.noIdeas": "目前沒有未排程想法。",
  "calendar.collapse": "收合",
  "calendar.items": "{count} 項",
  "task.count.open": "{count} 項未完成",
  "task.count.doing": "{count} 項執行中",
  "project.tab.current": "目前",
  "project.tab.completed": "已完成",
  "project.tab.archived": "封存",
  "project.view.list": "清單",
  "project.view.board": "狀態看板",
  "project.status.planning": "規劃中",
  "project.status.active": "進行中",
  "project.status.paused": "暫停",
  "project.status.done": "完成",
  "project.status.archived": "封存",
  "project.field.status": "狀態",
  "project.field.category": "分類",
  "project.field.importance": "重要性",
  "project.field.startDate": "開始日",
  "project.field.endDate": "結束日",
  "project.field.progress": "進度 {value}%",
  "project.importance.high": "高",
  "project.importance.medium": "中",
  "project.importance.low": "低",
  "project.importance.unset": "未設定",
  "project.hint.editImportance": "點一下或雙擊調整重要性",
  "project.focusToday": "今日焦點",
  "project.action.add": "新增專案",
  "project.action.open": "開啟專案看板",
  "project.action.save": "儲存專案",
  "project.action.complete": "完成專案",
  "project.complete.title": "完成這個專案？",
  "project.complete.message": "完成「{name}」？將同時完成 {count} 項未完成任務，並保留完整歷史。",
  "project.complete.messageNone": "完成「{name}」？這個專案沒有未完成任務。完整歷史會保留。",
  "project.complete.confirm": "確定完成",
  "project.complete.done": "「{name}」已完成",
  "project.action.reopen": "重新啟用專案",
  "project.action.archive": "封存專案",
  "project.action.delete": "永久刪除",
  "project.filter.status": "專案狀態篩選",
  "project.filter.importance": "專案重要性篩選",
  "project.filter.category": "專案分類篩選",
  "project.filter.allStatuses": "全部狀態",
  "project.filter.allImportance": "全部重要性",
  "project.filter.allCategories": "全部分類",
  "project.sort": "專案排序",
  "project.sort.importance": "重要性",
  "project.sort.status": "狀態",
  "project.sort.name": "名稱",
  "project.sort.endDate": "截止日",
  "project.empty": "沒有符合條件的專案。",
  "project.emptyHelp": "建立專案把明確成果變成可追蹤的工作，或調整篩選條件。",
  "project.emptyFirst": "還沒有專案。",
  "project.emptyFirstHelp": "新增一個專案，或之後從模板建立。",
  "project.emptyFirstAction": "從模板建立",
  "project.period.none": "未設期間",
  "project.date.undecided": "未定",
  "collection.title": "知識",
  "collection.description": "長期筆記與提示詞不需要專案狀態或期限。",
  "collection.action.add": "新增知識",
  "collection.action.delete": "刪除知識",
  "collection.fillCopy": "填變數並複製",
  "collection.fillHelp": "逐項填寫變數，完成後整支提示詞會複製到剪貼簿。",
  "collection.copy": "複製提示詞",
  "collection.filter.category": "知識分類篩選",
  "collection.filter.importance": "知識重要性篩選",
  "collection.empty": "尚未建立知識。",
  "collection.emptyHelp": "建立一篇長期筆記，或從「AI 提示詞 Plus」擴充匯入提示詞。",
  "collection.select": "選取知識即可查看 Markdown 內容。",
  "collection.contentHint": "尚無內容；可直接在 Markdown 中補充。",
  "entity.project.title": "新增規劃中專案",
  "entity.project.help": "適合需要多個行動、可明確完成的成果。",
  "entity.collection.title": "新增知識",
  "entity.collection.help": "適合會重複查閱、沒有完成期限的長期筆記或提示詞。",
  "knowledge.action.save": "存成知識",
  "knowledge.save.title": "存成知識",
  "knowledge.save.help": "會建成一篇長期筆記；原本的任務或日誌不會被改掉。",
  "project.relatedKnowledge": "相關知識",
  "project.relatedKnowledge.empty": "還沒有關聯的知識。",
  "entity.field.name": "名稱",
  "entity.field.category": "分類",
  "entity.field.importance": "重要性",
  "search.dialog": "搜尋任務、專案與知識",
  "search.keyword": "搜尋關鍵字",
  "search.placeholder": "A + B 聯集；A & B 交集；可用雙引號",
  "search.sort": "排序方式",
  "search.relevance": "關聯性",
  "search.date": "日期",
  "search.filter.status": "狀態篩選",
  "search.filter.kind": "類型篩選",
  "search.allStatuses": "全部狀態",
  "search.open": "進行中",
  "search.completed": "已完成與封存",
  "search.allKinds": "全部類型",
  "search.kind.task": "任務",
  "search.kind.project": "專案",
  "search.kind.collection": "知識",
  "search.results": "{count} 筆結果",
  "search.empty": "找不到相符的任務、專案或知識。",
  "search.help": "↑↓ 選擇 · Enter 開啟 · Esc 關閉",
  "search.goSettings": "前往設定",
  "board.back": "返回專案",
  "board.clearFilter": "清除專案篩選",
  "board.projectFilter": "依專案篩選看板",
  "board.title": "專案任務看板",
  "board.filteredTitle": "{name} · 任務看板",
  "board.description": "拖曳卡片即可改變階段；想法匣代表尚未承諾執行。",
  "board.table.description": "同一批任務以試算表顯示，可直接改狀態、專案或日期。",
  "board.list.description": "依階段分組的精簡清單。",
  "board.filteredDescription": "目前只顯示此專案的任務。",
  "board.allProjects": "全部專案",
  "board.dropHere": "拖到這裡",
  "board.moveUp": "往上",
  "board.moveDown": "往下",
  "sync.folder": "Markdown 資料夾",
  "sync.folderHelp": "按瀏覽資料夾即可用 Windows 選擇器，不需要手動貼路徑。",
  "sync.notSelected": "尚未選擇",
  "sync.browse": "瀏覽資料夾",
  "sync.manualPath": "或手動輸入路徑",
  "sync.useFolder": "使用此資料夾",
  "sync.cloud": "雲端同步服務",
  "sync.cloudHelp": "雲端同步是選用功能；此開源版本預設為本機模式，Markdown 正文不會上傳。",
  "sync.save": "儲存",
  "sync.pairing": "安全配對",
  "sync.pairingHelp": "網站現在只需要下方 8 位碼；不需要填 UUID 或其他安全密碼。",
  "sync.paired": "已完成安全配對",
  "sync.pairedHelp": "現在可以執行首次同步",
  "sync.enterCode": "請到網站輸入",
  "sync.openPairing": "在網站輸入配對碼",
  "sync.startPairing": "開始配對",
  "sync.recovery": "同步與復原",
  "sync.recoveryHelp": "寫入前自動建立 SHA-256 驗證 ZIP；背景只安靜檢查版本，有變更才同步。",
  "sync.firstConfirm": "還差最後一次確認",
  "sync.firstConfirmHelp": "先產生安全預覽；第一次同步完成後，才會啟用自動同步。",
  "sync.pairFirst": "請先完成配對",
  "sync.full": "立即完整同步",
  "sync.first": "完成首次同步",
  "sync.shadow": "切回 Shadow 模式",
  "layout.title": "整理成新架構",
  "layout.help": "預覽會列出將搬到 專案／知識／日誌／收件匣／模板／附件 的檔案。執行前會先做可驗證的 ZIP 備份。重複的檔案不會搬、也不會刪，請你選正本。",
  "layout.preview": "預覽整理",
  "layout.confirmTitle": "確認整理資料夾",
  "layout.confirmHelp": "以下檔案會搬到新資料夾，檔名不變，Obsidian 的 [[wikilink]] 大多仍可用。重複的不會搬、也不會刪。取消則不做任何變更。",
  "layout.moves": "將移動",
  "layout.duplicates": "重複（請選正本，不會刪）",
  "layout.empty": "這個資料夾已經是新架構，沒有需要移動的檔案。",
  "layout.apply": "執行整理",
  "layout.needFolder": "請先選擇 Markdown 資料夾。",
  "layout.done": "已整理成新架構",
  "layout.none": "沒有可移動的檔案",
};

export function translate(
  language: UiLanguage,
  key: string,
  values: Record<string, string | number> = {},
): string {
  const dictionary = language === "en" ? ENGLISH : TRADITIONAL_CHINESE;
  const template = dictionary[key] ?? key;
  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template,
  );
}
